import { Post } from "@prisma/client";
import type { NextPage } from "next";
import Head from "next/head";
import Container from "../components/Container";
import PostList from "../components/PostList";
import { prisma } from "../lib/prisma";

type Props = {
  posts: Post[];
};

const Home: NextPage<Props> = ({ posts }) => {
  console.log({ posts });
  return (
    <Container>
      <Head>
        <title>Atkins Jobs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PostList posts={posts} />
    </Container>
  );
};

export async function getServerSideProps() {
  const posts = await prisma.post.findMany({
    orderBy: { createdAt: "desc" },
    select: {
      id: true,
      company: true,
      createdAt: true,
      deadline: true,
      description: true,
      published: true,
      requiredSkills: true,
      recommendedSkills: true,
      status: true,
      title: true,
      updatedAt: true,
      url: true,
    },
  });
  return {
    props: { posts },
  };
}

export default Home;
